services:
  plugin-fastqc:
    # platform: linux/amd64
    build:
      context: ../../backend
      dockerfile: plugins/fastqc/.cloud/docker/Dockerfile
      target: plugin-dev
      args:
        - PLUGINNAME=fastqc
    image: parithera/fastqc-dev:latest
    restart: always
    volumes:
      - ../../backend:/codeclarity
      - ../../private:/private
      - ../../backend/plugins/fastqc/tests/fastq:/input
      - ../../backend/plugins/fastqc/tests/output:/output
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
      pg_bouncer:
        condition: service_started
      adminer:
        condition: service_started
    env_file:
      - ../../.cloud/env/.env.dev

volumes:
  projects:
